### ISSUE TITLE
ビルドツールをLaravel-Mix(Webpack)に集約したい。

### ISSUE THREAD

**Issue by ucan-lab** [ucan-lab/mixed-nuts#7]
## ビルド(アセット監視モード、ブラウザ自動リロード)

```
$ npm run watch
$ npm run gulp
```

`npm run gulp` で行なっている作業を `npm run watch` に集約したい。

## npm run gulpの作業

- EJSのビルド(gulp-ejs)
- HTMLの整形(gulp-html-beautify)
- ブラウザ自動リロード(BrowserSync)

## リンク

- https://readouble.com/laravel/5.5/ja/mix.html

**Comment by ucan-lab** [comment]
```
$ npm i -D browser-sync browser-sync-webpack-plugin
```

**Comment by ucan-lab** [comment]
```
// Browser Sync
mix.browserSync({
  proxy: "app.test",
  files: [
    "public/{*,**/*}"
  ]
});
```

`webpack.mix.js` に追記

```
$ npm run watch
> mixed-nuts@1.0.1 watch /Users/yuki/projects/mixed-nuts> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

              Asset     Size  Chunks                    Chunk Names
         /js/app.js  1.23 MB       0  [emitted]  [big]  /js/app
        /css/app.css 15.4 kB       0  [emitted]         /js/app
[Browsersync] Proxying: http://app.test
[Browsersync] Access URLs:
 ----------------------------------
       Local: http://localhost:3000
    External: http://10.0.1.2:3000
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.1.2:3001
 ----------------------------------
[Browsersync] Watching files...
```

- [ ] http://localhost:3000 => timeout...
- [x] http://localhost:3001 => OK
- [ ] http://10.0.1.2:3000 => timeout...
- [x] http://10.0.1.2:3001 => OK

3000ポートにアクセスできない...謎ぃ

**Comment by ucan-lab** [comment]
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/browsersync.md
ドキュメントを読むとLaravel-mixはBrowserSyncをサポートしている。

```
mix.browserSync('my-domain.dev');

// Or:

mix.browserSync({
    proxy: 'my-domain.dev'
})
```

- [BrowserSync Option Document](https://browsersync.io/docs/options)

**Comment by ucan-lab** [comment]
https://github.com/JeffreyWay/laravel-mix/issues

Laravel-mixのIssueにはBrowserSyncのバグ報告ないみたい。
実際使う人自体少ない気がするが...

**Comment by ucan-lab** [comment]
https://github.com/Browsersync/browser-sync/issues

BrowserSyncのイシュー多すぎ問題（351件オープンしてる）
それっぽい問題を探してみる...（not working, timeout, webpack など）

```
https://github.com/BrowserSync/browser-sync/issues/1434
https://github.com/BrowserSync/browser-sync/issues/1502
https://github.com/BrowserSync/browser-sync/issues/1491
https://github.com/BrowserSync/browser-sync/issues/1449
https://github.com/BrowserSync/browser-sync/issues/1434
```

**Comment by ucan-lab** [comment]
https://github.com/bazilio91/ejs-compiled-loader

EJSのコンパイルにはこのローダーを使いたい。

**Comment by ucan-lab** [comment]
# Laravel-mix メモ

## 実行順

https://github.com/JeffreyWay/laravel-mix/blob/master/src/index.js
https://github.com/JeffreyWay/laravel-mix/blob/master/src/config.js
https://github.com/JeffreyWay/laravel-mix/blob/master/src/Mix.js

## Full API

https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.mix.js

### WebpackConfig

https://github.com/JeffreyWay/laravel-mix/blob/master/src/Api.js#L310-L329
https://github.com/JeffreyWay/laravel-mix/blob/master/src/builder/WebpackConfig.js

### BrowserSync

https://github.com/JeffreyWay/laravel-mix/blob/master/src/Api.js#L310-L329

**Comment by rinne-grid** [comment]
とりあえず、ejsのビルドとBrowserSyncの起動について、npm run watchのみで動くようにしました。
ブランチ：feature/#7

https://github.com/ucan-lab/mixed-nuts/tree/feature/%237

### 変更点

* ejsのincludeの起点をresoucesに変更（相対パスのやり方を検討する必要あり？）
  * webpackでのビルド時にinclude()関数が動作しなかったため、普通のincludeに変更
* webpack.mix.jsに設定を追記
  * ejsページごとに、HtmlWebpackPluginを記述するやり方になってる
  * 参考にしたページ：https://qiita.com/tomi_shinwatec/items/0601eee63c6df651ff3a
* 導入したモジュール
  * browser-sync-webpack-plugin
  * ejs-compiled-loader
  * extract-loader
  * html-loader
  * html-webpack-plugin
